import type { Container, User } from "./types";

export const DEMO_USER: User & { password: string } = {
  id: "usr_001",
  email: "operator@harbor.dev",
  password: "harbor123",
  name: "Yard Operator",
  role: "operator",
  company: "Harbor Terminal Services",
};

export const CONTAINERS: Container[] = [
  {
    id: "MSKU7482913",
    isoType: "40HC",
    line: "Maersk",
    vessel: "Maersk Kowloon",
    voyage: "214W",
    status: "Gate Out Ready",
    yardPosition: "B-12-04-3",
    dischargedAt: "2026-08-21",
    freeDaysRemaining: 3,
    grossWeightKg: 24180,
    holds: [],
    consignee: "Gulf Metals Trading LLC",
  },
  {
    id: "MSCU4419087",
    isoType: "20GP",
    line: "MSC",
    vessel: "MSC Aurora",
    voyage: "331E",
    status: "In Yard",
    yardPosition: "A-03-11-1",
    dischargedAt: "2026-08-23",
    freeDaysRemaining: 5,
    grossWeightKg: 18740,
    holds: ["Customs"],
    consignee: "Emirates Polymer Co.",
  },
  {
    id: "CMAU6620451",
    isoType: "40RF",
    line: "CMA CGM",
    vessel: "CMA CGM Zephyr",
    voyage: "108W",
    status: "In Yard",
    yardPosition: "R-01-02-2",
    dischargedAt: "2026-08-24",
    freeDaysRemaining: 6,
    grossWeightKg: 27650,
    holds: [],
    consignee: "Fresh Harvest Foods",
  },
  {
    id: "HLXU3388216",
    isoType: "40HC",
    line: "Hapag-Lloyd",
    vessel: "Hamburg Bridge",
    voyage: "077N",
    status: "On Hold",
    yardPosition: "C-08-06-4",
    dischargedAt: "2026-08-18",
    freeDaysRemaining: 0,
    grossWeightKg: 22310,
    holds: ["Payment", "Documentation"],
    consignee: "Northline Industrial",
  },
  {
    id: "MSKU9051772",
    isoType: "20GP",
    line: "Maersk",
    vessel: "Maersk Kowloon",
    voyage: "214W",
    status: "Gate Out Ready",
    yardPosition: "B-12-05-1",
    dischargedAt: "2026-08-21",
    freeDaysRemaining: 3,
    grossWeightKg: 15980,
    holds: [],
    consignee: "Gulf Metals Trading LLC",
  },
  {
    id: "OOLU8123640",
    isoType: "40GP",
    line: "OOCL",
    vessel: "OOCL Meridian",
    voyage: "455E",
    status: "Discharged",
    yardPosition: "D-02-01-1",
    dischargedAt: "2026-08-25",
    freeDaysRemaining: 7,
    grossWeightKg: 26040,
    holds: [],
    consignee: "Sharjah Auto Parts",
  },
  {
    id: "TGHU5567029",
    isoType: "40RF",
    line: "Evergreen",
    vessel: "Ever Lyric",
    voyage: "092W",
    status: "In Yard",
    yardPosition: "R-01-04-1",
    dischargedAt: "2026-08-22",
    freeDaysRemaining: 4,
    grossWeightKg: 28900,
    holds: [],
    consignee: "Fresh Harvest Foods",
  },
  {
    id: "MSCU7734158",
    isoType: "40HC",
    line: "MSC",
    vessel: "MSC Aurora",
    voyage: "331E",
    status: "Loaded",
    yardPosition: "—",
    dischargedAt: "2026-08-15",
    freeDaysRemaining: 0,
    grossWeightKg: 23470,
    holds: [],
    consignee: "Delta Chemicals FZE",
  },
  {
    id: "CMAU2298310",
    isoType: "20GP",
    line: "CMA CGM",
    vessel: "CMA CGM Zephyr",
    voyage: "108W",
    status: "On Hold",
    yardPosition: "A-05-09-2",
    dischargedAt: "2026-08-19",
    freeDaysRemaining: 1,
    grossWeightKg: 17220,
    holds: ["Customs"],
    consignee: "Emirates Polymer Co.",
  },
  {
    id: "HLXU6640933",
    isoType: "40GP",
    line: "Hapag-Lloyd",
    vessel: "Hamburg Bridge",
    voyage: "077N",
    status: "Gate Out Ready",
    yardPosition: "C-08-02-1",
    dischargedAt: "2026-08-20",
    freeDaysRemaining: 2,
    grossWeightKg: 25110,
    holds: [],
    consignee: "Northline Industrial",
  },
  {
    id: "MSKU1204488",
    isoType: "40HC",
    line: "Maersk",
    vessel: "Maersk Sentinel",
    voyage: "188W",
    status: "In Yard",
    yardPosition: "B-14-07-2",
    dischargedAt: "2026-08-24",
    freeDaysRemaining: 6,
    grossWeightKg: 21630,
    holds: [],
    consignee: "Sharjah Auto Parts",
  },
  {
    id: "OOLU4471205",
    isoType: "20GP",
    line: "OOCL",
    vessel: "OOCL Meridian",
    voyage: "455E",
    status: "In Yard",
    yardPosition: "D-02-05-3",
    dischargedAt: "2026-08-25",
    freeDaysRemaining: 7,
    grossWeightKg: 16490,
    holds: [],
    consignee: "Delta Chemicals FZE",
  },
];
